"""The UN cards that belong to a shipment, served from the imported store.

Cards are EMCargo's own generated datasheets — one per UN number *and*
modality (``UN1203_ADR.pdf``), built by the **Generate UN cards** workflow
from the measured regulatory tables and imported by an administrator into
the persistent store (see :mod:`.un_card_store`). A shipment only ever needs
the handful of cards for the substances the user declared on the regimes the
journey actually touches, so the export bundles exactly those into a zip.

When no set has been imported — a fresh installation, or one that chooses
not to — the feature reports that no cards are available instead of
breaking the export. A missing card for one regime never borrows another
regime's card: the regimes print different obligations.
"""
from __future__ import annotations

import io
import os
import re
import tempfile
import zipfile
from pathlib import Path
from typing import Any

from .un_card_store import MODALITIES, card_path, installed_manifest, status as store_status

#: The wizard speaks in DG profiles; the card set speaks in modalities.
#: The only mismatch is air, where the profile is named after the IATA DGR
#: while the card set (if a source is ever licensed) follows the ICAO TI.
#:
#: ``IATA_DGR`` is the spelling the wizard actually sends — it is the value in
#: the document registry and in the frontend's modality table. It was missing
#: here, and a profile that is not in this map is not simply ignored: it makes
#: :func:`_modalities_for` fall through to *every* modality, so an air-only
#: shipment asked for road, rail, inland and sea cards as well.
PROFILE_TO_MODALITY = {
    "ADR": "ADR",
    "RID": "RID",
    "ADN": "ADN",
    "IMDG": "IMDG",
    "IATA": "ICAO",
    "IATA_DGR": "ICAO",
    "ICAO": "ICAO",
}


def reset_cache() -> None:
    """Nothing is cached any more; kept so existing callers stay valid."""


def has_un_cards() -> bool:
    return installed_manifest() is not None


def card_count() -> int:
    """How many cards the installed set holds, across all modalities."""
    return int(store_status().get("total_cards") or 0)


def _modalities_for(profiles: list[str] | None) -> list[str]:
    wanted = []
    for profile in profiles or []:
        modality = PROFILE_TO_MODALITY.get(str(profile).strip().upper())
        if modality and modality not in wanted:
            wanted.append(modality)
    return wanted or list(MODALITIES)


def un_numbers_in(dangerous_goods: list[dict[str, Any]] | None) -> list[str]:
    """The UN numbers the user declared, in order, without duplicates."""
    seen: list[str] = []
    for entry in dangerous_goods or []:
        for product in entry.get("products") or []:
            raw = str(product.get("un_number") or "").strip()
            digits = re.sub(r"\D", "", raw)
            if len(digits) == 4 and digits not in seen:
                seen.append(digits)
    return seen


def availability(dangerous_goods: list[dict[str, Any]] | None,
                 profiles: list[str] | None = None) -> dict[str, Any]:
    """Which of the shipment's UN numbers we hold a card for, per regime."""
    requested = un_numbers_in(dangerous_goods)
    modalities = _modalities_for(profiles)
    cards: list[dict[str, str]] = []
    available: list[str] = []
    for un in requested:
        found_any = False
        for modality in modalities:
            path = card_path(un, modality)
            if path is not None:
                cards.append({"un_number": un, "modality": modality,
                              "file": path.name})
                found_any = True
        if found_any:
            available.append(un)
    return {
        "enabled": has_un_cards(),
        "requested": requested,
        "modalities": modalities,
        "available": available,
        "missing": [un for un in requested if un not in available],
        "cards": cards,
        "count": len(cards),
    }


def build_zip(dangerous_goods: list[dict[str, Any]] | None,
              profiles: list[str] | None = None) -> tuple[Path, dict[str, Any]]:
    """Bundle this shipment's cards. Raises FileNotFoundError without any."""
    result = availability(dangerous_goods, profiles)
    if not result["cards"]:
        raise FileNotFoundError("no UN cards available for this shipment")

    fd, name = tempfile.mkstemp(suffix=".zip")
    os.close(fd)
    out_path = Path(name)
    try:
        out_path.chmod(0o600)
    except OSError:
        pass

    manifest = installed_manifest() or {}
    readme = io.StringIO()
    readme.write(
        "UN cards for this shipment\n"
        "==========================\n\n"
        "One card per UN number and regime you declared, generated by\n"
        "EMCargo from the regulatory tables its compliance checks run on.\n"
        "A compilation offered as an aid; the published text of each\n"
        "regulation remains authoritative, and these sheets are not part of\n"
        "the transport documentation.\n\n"
        f"Card set generated: {manifest.get('generated_at', 'unknown')}\n"
        f"Editions: {manifest.get('editions', {})}\n\n"
    )
    for card in result["cards"]:
        readme.write(f"  UN {card['un_number']}  {card['modality']}  ->  {card['file']}\n")
    if result["missing"]:
        readme.write(
            "\nNo card is held for the following UN numbers on the selected"
            " regimes:\n" + "".join(f"  UN {un}\n" for un in result["missing"]))

    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for card in result["cards"]:
            path = card_path(card["un_number"], card["modality"])
            if path is not None:
                archive.write(path, arcname=path.name)
        archive.writestr("README.txt", readme.getvalue())

    return out_path, result
