"""Handing the user the UN cards for their own substances, per regime.

The point of the feature is selectivity twice over: a shipment of gasoline by
road gets the gasoline ADR card — not the chlorine card, and not the IMDG
card of a journey that never touches a ship. It also has to stay out of the
way when no card set has been imported, which is the state of every fresh
installation now that the cards live in a downloadable release instead of
the image.
"""
import json
import zipfile

import pytest

from app.core.config import get_settings
from app.services.documents import un_cards


def _write_card(base, modality, un):
    directory = base / modality
    directory.mkdir(parents=True, exist_ok=True)
    (directory / f"UN{un}_{modality}.pdf").write_bytes(
        b"%PDF-1.4\n% card UN" + un.encode() + b" " + modality.encode() + b"\n%%EOF\n")


@pytest.fixture
def store(tmp_path, monkeypatch):
    """A small installed card set: 1203 on ADR+ADN+IMDG, 1017 on ADR only."""
    monkeypatch.setenv("DATA_DIR", str(tmp_path))
    get_settings.cache_clear()
    base = tmp_path / "un-cards"
    base.mkdir()
    for modality in ("ADR", "ADN", "IMDG"):
        _write_card(base, modality, "1203")
    _write_card(base, "ADR", "1017")
    (base / "manifest.json").write_text(json.dumps({
        "schema_version": 1,
        "generated_at": "2026-08-19T12:00:00Z",
        "editions": {"ADR": "ADR 2025"},
    }), encoding="utf-8")
    yield base
    get_settings.cache_clear()


@pytest.fixture
def no_store(tmp_path, monkeypatch):
    monkeypatch.setenv("DATA_DIR", str(tmp_path))
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


def dg(*un_numbers):
    return [{"line_id": 1, "products": [{"un_number": un} for un in un_numbers]}]


def test_only_the_declared_substances_and_regimes_are_bundled(store):
    path, status = un_cards.build_zip(dg("1203"), profiles=["ADR"])
    try:
        names = zipfile.ZipFile(path).namelist()
    finally:
        path.unlink(missing_ok=True)
    assert status["available"] == ["1203"]
    assert sorted(n for n in names if n.endswith(".pdf")) == ["UN1203_ADR.pdf"]


def test_a_multimodal_shipment_gets_each_regimes_own_card(store):
    status = un_cards.availability(dg("1203"), profiles=["ADR", "IMDG"])
    assert [(c["modality"]) for c in status["cards"]] == ["ADR", "IMDG"]
    assert status["count"] == 2


def test_no_regime_borrows_another_regimes_card(store):
    """UN 1017 only has an ADR card here; asking for the sea leg must not
    quietly hand over the road card."""
    status = un_cards.availability(dg("1017"), profiles=["IMDG"])
    assert status["available"] == []
    assert status["missing"] == ["1017"]


def test_the_iata_profile_maps_to_the_icao_card_set(store):
    status = un_cards.availability(dg("1203"), profiles=["IATA"])
    assert status["modalities"] == ["ICAO"]
    assert status["available"] == []


def test_empty_profiles_mean_every_installed_regime(store):
    status = un_cards.availability(dg("1203"), profiles=[])
    assert {c["modality"] for c in status["cards"]} == {"ADR", "ADN", "IMDG"}


def test_the_zip_explains_itself(store):
    path, _ = un_cards.build_zip(dg("1203", "9999"), profiles=["ADR"])
    try:
        readme = zipfile.ZipFile(path).read("README.txt").decode()
    finally:
        path.unlink(missing_ok=True)
    assert "UN 1203" in readme
    assert "No card is held" in readme and "UN 9999" in readme
    assert "generated by\nEMCargo" in readme or "generated by EMCargo" in readme
    assert "Cantell" not in readme


def test_un_numbers_are_read_from_the_declared_products(store):
    entries = [
        {"line_id": 1, "products": [{"un_number": "UN 1203"}, {"un_number": "1017"}]},
        {"line_id": 2, "products": [{"un_number": "1203"}]},  # duplicate
        {"line_id": 3, "products": [{"un_number": ""}]},
    ]
    assert un_cards.un_numbers_in(entries) == ["1203", "1017"]


def test_without_a_store_the_feature_reports_itself_unavailable(no_store):
    assert un_cards.has_un_cards() is False
    status = un_cards.availability(dg("1203"))
    assert status["enabled"] is False
    assert status["available"] == []
    with pytest.raises(FileNotFoundError):
        un_cards.build_zip(dg("1203"))


def test_a_shipment_without_dangerous_goods_asks_for_nothing(store):
    assert un_cards.availability(None)["available"] == []
    with pytest.raises(FileNotFoundError):
        un_cards.build_zip(None)


def test_card_count_counts_cards_not_un_numbers(store):
    assert un_cards.card_count() == 4
