"""UN reference cards using EMCargo's shared dossier typography and colours.

Each source entry begins on a new page. Flowing tables retain all source
values and continue across pages; no regulatory text is shrunk or clipped.
Hazard artwork remains the label renderer's unmodified vector drawing.
This offline module imports only the standalone PDF theme, never web settings.
"""
from __future__ import annotations

import sys
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    BaseDocTemplate, Flowable, Frame, NextPageTemplate, PageBreak,
    PageTemplate, Paragraph, Spacer, Table, TableStyle,
)

from .labels import draw_label
from .sources.base import REPO, CardPage

sys.path.insert(0, str(REPO / "backend"))
from app.pdf_style import (
    ACCENT, ASSETS, BOLD, LINE, MARGIN, MUTED, TEXT,
    SectionHeading, draw_wordmark, paragraph_styles, table_commands,
)

PAGE_W, PAGE_H = A4
FRAME_W = PAGE_W - 2 * MARGIN


def _p(value: str, style) -> Paragraph:
    paragraph = SectionHeading if style.name == "emcargo_section" else Paragraph
    return paragraph(escape(str(value)).replace("\n", "<br/>"), style)


def _fields(rows: list[tuple[str, str]], styles: dict, width: float = FRAME_W) -> Table:
    data = [[_p(label, styles["label"]), _p(value, styles["cell"])]
            for label, value in rows]
    table = Table(data, colWidths=[width * .30, width * .70],
                  splitByRow=1, splitInRow=1, hAlign="LEFT")
    table.setStyle(TableStyle(table_commands(header=False)))
    return table


def _attributes(rows: list[tuple[str, str]], styles: dict) -> Table:
    """Three readable cells per row, with labels above their full values."""
    data = []
    for offset in range(0, len(rows), 3):
        cells = [[_p(label, styles["label"]), _p(value, styles["value"])]
                 for label, value in rows[offset:offset + 3]]
        data.append(cells + [""] * (3 - len(cells)))
    table = Table(data, colWidths=[FRAME_W / 3] * 3,
                  splitByRow=1, splitInRow=1, hAlign="LEFT")
    table.setStyle(TableStyle(table_commands(header=False)))
    return table


class _HazardLabels(Flowable):
    """Illustrations only; the separate printable label sheet owns print sizes."""

    def __init__(self, codes: list[str]):
        super().__init__()
        self.codes = codes
        self.width = FRAME_W
        self.height = ((len(codes) + 7) // 8) * 62

    def draw(self):
        for index, code in enumerate(self.codes):
            draw_label(self.canv, code, (index % 8) * 60,
                       self.height - (index // 8 + 1) * 62 + 8, 46)


def _frame(canvas, doc, entry: CardPage, index: int, count: int, generated_at: str,
           styles: dict, logo: bytes | None) -> None:
    canvas.saveState()
    canvas.setFillColor(ACCENT)
    canvas.rect(0, PAGE_H - 3, PAGE_W, 3, stroke=0, fill=1)
    draw_wordmark(canvas, MARGIN, PAGE_H - 42, logo=logo)
    canvas.setFont(TEXT, 7.4)
    canvas.setFillColor(MUTED)
    title = f"{entry.modality} – UN Card · UN {entry.un}"
    canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - 36, title)
    if count > 1:
        canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - 47, f"entry {index} of {count}")
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(.6)
    canvas.line(MARGIN, PAGE_H - 60, PAGE_W - MARGIN, PAGE_H - 60)
    canvas.line(MARGIN, 68, PAGE_W - MARGIN, 68)
    disclaimer = _p("Generated by EMCargo — a compilation offered as an aid; the published "
                    "text of the regulation remains authoritative.", styles["disclaimer"])
    _, height = disclaimer.wrap(FRAME_W - 55, 100)
    disclaimer.drawOn(canvas, MARGIN, 59 - height)
    canvas.setFont(TEXT, 6.6)
    canvas.setFillColor(MUTED)
    canvas.drawString(MARGIN, 22, f"Regulation: {entry.regulation} · Generated: {generated_at}")
    canvas.setFont(BOLD, 7.5)
    canvas.setFillColor(ACCENT)
    canvas.drawRightString(PAGE_W - MARGIN, 44, str(doc.page))
    canvas.restoreState()


def render_card_pdf(path: Path, pages: list[CardPage], generated_at: str) -> None:
    styles = paragraph_styles()
    first = pages[0]
    doc = BaseDocTemplate(str(path), pagesize=A4,
                          leftMargin=MARGIN, rightMargin=MARGIN,
                          topMargin=82, bottomMargin=82,
                          title=f"UN {first.un} — {first.modality} UN Card",
                          author="EMCargo",
                          subject=f"{first.regulation} reference card for UN {first.un}")
    logo_path = ASSETS / "logo.png"
    logo = logo_path.read_bytes() if logo_path.is_file() else None
    story = []
    for index, page in enumerate(pages, start=1):
        template = f"entry-{index}"
        frame = Frame(MARGIN, doc.bottomMargin, doc.width, doc.height,
                      leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)
        doc.addPageTemplates(PageTemplate(
            id=template, frames=[frame],
            onPage=lambda canvas, document, entry=page, number=index:
                _frame(canvas, document, entry, number, len(pages), generated_at, styles, logo)))
        if index > 1:
            story.extend([NextPageTemplate(template), PageBreak()])
        story.extend([
            _p(f"UN {page.un}", styles["title"]),
            _p(f"{page.modality} · {page.regulation}", styles["status"]),
            _p("Shipping name", styles["section"]),
            _fields([(language.upper(), page.names[language])
                     for language in ("en", "nl", "de", "fr") if page.names.get(language)], styles),
            Spacer(1, 10),
            _attributes([("Class", page.klass), ("Packing group", page.packing_group),
                         ("Classification code", page.classification_code),
                         *page.identity_extra], styles),
            _p("Hazard labels", styles["section"]),
        ])
        if page.labels:
            story.append(_HazardLabels(page.labels))
        else:
            story.append(_p("No labels in column (5).", styles["note"]))
        story.append(_fields([("Hazard labels", ", ".join(page.labels) or "—"),
                              *page.label_extra, ("Marking", page.marking)], styles))
        if page.packaging_rows:
            story.extend([_p("Packaging", styles["section"]), _fields(page.packaging_rows, styles)])
        if page.tank_rows:
            story.extend([Spacer(1, 10), _attributes(page.tank_rows, styles)])
        if page.provision_rows:
            story.extend([_p("Special transport provisions", styles["section"]),
                          _fields(page.provision_rows, styles)])
        if page.lq_eq is not None:
            lq, eq = page.lq_eq
            rows = [("Limited quantities (LQ)", lq)]
            if eq:
                rows.append(("Excepted quantities (EQ)", eq))
            story.extend([Spacer(1, 10), _attributes(rows, styles)])
        # Full provenance belongs in flowing content, so a long source never
        # disappears beyond a two-line footer limit.
        story.extend([_p("Source", styles["section"]), _p(page.source, styles["note"])])
    doc.build(story)
