"""Validate a generated UN card set against its own manifest.

Run after generation, before anything is published:

    python scripts/un_cards/validate.py --dir /tmp/cards

Checks, per card the manifest lists: the file exists, is not empty, starts
with %PDF, matches its recorded SHA-256 and size, its filename carries the
UN number and modality the manifest claims, the PDF's own text repeats that
UN number and the EMCargo footer, and no third-party branding leaked in.
A set that fails any check must not be published — the exit code says so.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import fitz

FILENAME = re.compile(r"^(ADR|RID|ADN|IMDG|ICAO)/UN(\d{4})_(ADR|RID|ADN|IMDG|ICAO)\.pdf$")

#: Branding that must never appear on a EMCargo card. The old card set was
#: third-party artwork; these strings guard against any path that would leak
#: it back in.
FORBIDDEN = ("Cantell", "cantell")


def validate(directory: Path, sample_text_every: int = 1) -> dict:
    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
    problems: list[str] = []
    checked = 0
    text_checked = 0

    for index, card in enumerate(manifest["cards"]):
        name = card["file"]
        match = FILENAME.match(name)
        if not match:
            problems.append(f"{name}: filename does not follow UN####_<MODALITY>.pdf")
            continue
        if match.group(1) != match.group(3) or match.group(1) != card["modality"]:
            problems.append(f"{name}: directory, suffix and manifest modality disagree")
        if match.group(2) != card["un_number"]:
            problems.append(f"{name}: filename UN and manifest UN disagree")

        path = directory / name
        if not path.is_file():
            problems.append(f"{name}: missing")
            continue
        content = path.read_bytes()
        if not content:
            problems.append(f"{name}: empty file")
            continue
        if not content.startswith(b"%PDF"):
            problems.append(f"{name}: does not start with %PDF")
        if len(content) != card["size"]:
            problems.append(f"{name}: size {len(content)} != manifest {card['size']}")
        if hashlib.sha256(content).hexdigest() != card["sha256"]:
            problems.append(f"{name}: sha256 mismatch against manifest")
        checked += 1

        if index % sample_text_every == 0:
            with fitz.open(stream=content, filetype="pdf") as doc:
                text = "".join(page.get_text() for page in doc)
            if f"UN {card['un_number']}" not in text and card["un_number"] not in text:
                problems.append(f"{name}: UN number not found in the PDF text")
            if "Generated by EMCargo" not in text:
                problems.append(f"{name}: EMCargo footer missing")
            for term in FORBIDDEN:
                if term in text:
                    problems.append(f"{name}: forbidden branding '{term}' present")
            text_checked += 1

    listed = {card["file"] for card in manifest["cards"]}
    for stray in directory.glob("*/UN*.pdf"):
        relative = f"{stray.parent.name}/{stray.name}"
        if relative not in listed:
            problems.append(f"{relative}: on disk but not in the manifest")

    return {
        "cards_in_manifest": len(manifest["cards"]),
        "files_checked": checked,
        "texts_checked": text_checked,
        "problems": problems,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dir", required=True, type=Path)
    parser.add_argument("--sample-text-every", type=int, default=1,
                        help="text-check every Nth card (1 = all)")
    args = parser.parse_args()
    result = validate(args.dir, args.sample_text_every)
    print(json.dumps({**result, "problems": result["problems"][:50]}, indent=1))
    if result["problems"]:
        print(f"VALIDATION FAILED: {len(result['problems'])} problem(s)", file=sys.stderr)
        return 1
    print("validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
